application: wongthesis
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- appstats: on
- remote_api: on
- admin_redirect: on

handlers:

- url: /static
  static_dir: static
  secure: optional
  expiration: "30d"

- url: /.*
  script: main.py
  secure: optional
